<?php include "header.phtml"; ?>
<h1>This is your Basket</h1>
<p>It's where you decide what to do with the items you have selected.</p>
<form action="basket.php" method="post">
	<input type="submit" name="basketRemove" value="Remove from basket" />
	<input type="submit" name="clearBasket" value="Clear your basket" />
	<input type="submit" name="Checkout" value="Checkout!" />
	<table>
		<tr>
			<th>Food Type</th>
			<th>Category</th>
			<th>Description</th>
			<th>Price</th>
			<th>Select</th>
		</tr>
			<?php foreach ($this->basket_food as $food): ?>
			    <tr>
			        <td><?=$food["foodtype"]?></td>
			        <td><?=$food["category"]?></td>
			        <td><?=$food["description"]?></td>
			        <td><?=$food["price"]?></td>
			        <td><input type="checkbox" name="basketSelect[]" value="<?=$food["ref"]?>" />
			    </tr>
			<?php endforeach; ?>
		<tr>
			<td class="totalcost" colspan="3">Total cost:</td>
			<td><?=$this->total_cost; ?></td>
		</tr>
	</table>
	<input type="submit" name="basketRemove" value="Remove from basket" />
	<input type="submit" name="clearBasket" value="Clear your basket" />
	<input type="submit" name="Checkout" value="Checkout!" />
</form>
<?php include "footer.phtml"; ?>