</div>
		<div id="footer">
			<small>&copy; Curtis Griffiths - cug1@aber.ac.uk</small><br />
			<small>By using this website you confirm you have read the 
				<b><a href="about.php">disclaimer</a></b> on the 
				<a href="about.php">about page</a>.</small><br />
			<p>
			<a href="http://jigsaw.w3.org/css-validator/check/referer">
				<img style="border:0;width:88px;height:31px" 
				src="http://jigsaw.w3.org/css-validator/images/vcss-blue" 
				alt="Valid CSS!" /></a>
		
    		<a href="http://validator.w3.org/check?uri=referer">
    		<img src="http://www.w3.org/Icons/valid-xhtml10-blue" 
    		alt="Valid XHTML 1.0 Strict" height="31" width="88" /></a>
  		</p>
		</div>
	</div>

</body>
</html>