<?php include "header.phtml"; ?>
<h1>Welcome to Curtis' online food shop</h1>
<p>To login to the food shop please enter your name into the text box provided, this will then take you to the products page where you can egin your shopping session.</p>
<p>If you would like to view the documentation please use the link to the <a href="about.php"> about page on the navigation bar</p>
<p><b>This is not a real web shop</b>, </a>if you'd like some more
information please look at the <a href="about.php">about page</a>. For the <a href="about.php">Declaration of origonality</a>, use the <a href="about.php">about link</a>. There is also a
<b><a href="about.php">disclaimer</a></b> that should be read.</p>
<?php include "footer.phtml"; ?>